blog/urls.py
from django.conf.urls import url
from . import views


app_name = 'blog'

urlpatterns = [
    url(r'^blog/admin$', views.blog_admin, name='blog_admin'),
    url(r'^blog$', views.blog_posts, name='blog_posts'),
    url(r'^blog/new$', views.create_post, name='create_post'),
    url(r'^blog/edit/(?P<pk>\d+)$', views.update_post, name='update_post'),
    url(r'^blog/delete/(?P<pk>\d+)$', views.delete_post, name='delete_post'),
]

dreamnight/urls.py
from django.conf.urls import url
from . import views


app_name = 'dreamnight'
urlpatterns = [
    url(r'^$', views.homepage, name='homepage'),
]

nightsite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('dreamnight.urls')),
    url(r'', include('blog.urls')),
]

blog/models.py
from django.db import models
from django_bleach.models import BleachField
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    text = BleachField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

blog/forms.py
from django import forms

from .models import Post


# post form class
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'text']
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'input-title col-sm-12',
                'placeholder': 'Title...',
            }),
            'text': forms.Textarea(attrs={
                'class': 'input-text col-sm-12',
                'placeholder': 'Type the text here...',
            }),
        }

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.utils import timezone

from .models import Post
from .forms import PostForm


# blog
@login_required
def blog_admin(request):
    posts = Post.objects.all().order_by('-created_date')
    template_name = "blog/blog_admin.html"
    data = {'posts': posts}
    return render(request, template_name, data)

def blog_posts(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by(
        '-published_date')
    template_name = "blog/blog_posts.html"
    data = {'posts': posts}
    return render(request, template_name, data)

def blog_post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/blog_post_detail.html', {'post': post})

# CRUD
@login_required
def create_post(request):
    if request.method == 'POST' and 'save' in request.POST:
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('blog:blog_admin')
    elif request.method == 'POST' and 'publish' in request.POST:
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('blog:blog_admin')
    else:
        form = PostForm()
    return render(request, 'blog/blog_form.html', {'form': form})

@login_required
def update_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('blog:blog_admin')
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/blog_form.html',  {'form': form})

@login_required
def delete_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        if 'not-sure' in request.POST:
            return redirect('blog:blog_admin')
        post.delete()
        return redirect('blog:blog_admin')
    return render(request, 'blog/blog_confirm_delete.html', {'object': post})

dreamnight/views.py
from django.shortcuts import render


def homepage(request):
    return render(request, "dreamnight/homepage.html", {})

templates/blog/blog_admin.html
{% extends 'core/base.html' %}

{% block content %}
  <div class="row post-list-container">
    <div class="container">
      <div class="col-sm-offset-1 col-sm-10 blog-admin-header">
        <h2>Posts list</h2>
        <a href="{% url 'blog:create_post' %}"><button class='btn btn-success btn-sm pull-right' title="Create new post">Create</button></a><br /><br />
      </div>
      <div class="col-sm-offset-1 col-sm-10">
        <table class="table table-responsive bg-lightgrey">
          <tr class="bg-lightblack">
            <th>Post Name</th>
            <th>Author</th>
            <th>Created Date</th>
            <th>Published Date</th>
            <th class="bg-white info">Edit</th>
            <th class="bg-white danger">Delete</th>
          </tr>
          {% for post in posts %}
            <tr>
              <th>{{ post.title }}</th>
              <td>{{ post.author }}</td>
              <td>{{ post.created_date }}</td>
              <td>{{ post.published_date }}</td>
              <td><a href="{%	url	'blog:update_post'	pk=post.pk	%}" title="Edit post">Edit</a></td>
              <td><a href="{%  url 'blog:delete_post' pk=post.pk %}" title="Delete post" style="color:red;">Delete</a></td>
            </tr>
          {% endfor %}
        </table>
      </div>
    </div>
  </div>
{% endblock %}

templates/blog/blog_confirm_delete.html
{% extends 'core/base.html' %}
{% block content %}
<div class="row">
  <div class="col-sm-offset-1 col-sm-10 delete-form">
    <form method="post">{% csrf_token %}
      <h2>Are you sure you want to delete post "{{ object }}" ?</h2>
      <div class="btn-group-lg">
        <button type="submit" class="btn btn-danger" name="i-am-sure">Yes, I'm sure</button>
        <button type="submit" class="btn btn-info" name="not-sure">No, Take me back</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

templates/blog/blog_form.html
{% extends 'core/base.html' %}

{% block content %}
  <div class="row blog-form-container">
    <div class="col-sm-offset-1 col-sm-9">
      <a href="{% url 'blog:blog_admin' %}"><button class="btn btn-danger btn-sm" title="Back to post lists">Back</button></a>
      <p class="text-center blog-form-title">Create or Edit post</p>
      <form method="post" id="post-form">{% csrf_token %}
        {% for field in form %}
          <div class="col-sm-1">{{ field.label_tag }}</div>
          <div class="col-sm-11">{{ field }}</div>
        {% endfor %}
        <div class="col-xs-1 visible-xs btn-bottom-xs">
          <button type="submit" name="save" class="btn btn-success btn-sm" form="post-form" title="Save post">Save</button>
          <button type="submit" name="publish" class="btn btn-info btn-sm" form="post-form" title="Publish post">Publish</button>
        </div>
      </form>
    </div>
    <div class="col-sm-offset-10 col-sm-1 affix hidden-xs btn-fixed-right">
      <button type="submit" name="save" class="btn btn-success btn-sm" form="post-form"  title="Save post">Save</button>
      <button type="submit" name="publish" class="btn btn-info  btn-sm" form="post-form" title="Publish post">Publish</button>
    </div>
  </div>
{% endblock %}

templates/blog/blog_post_detail.html
{% extends 'core/base.html' %}

{% block content %}
<div class="col-sm-offset-2 col-sm-8">
  <div class="col-sm-2 post-header dotted-bottom">
    <div class="post-title">{{ post.title }}</div>
    {% if post.published_date %}
      <div class="post-date">{{ post.pusblished_date }}</div>
    {% endif %}
  </div>
  <div class="col-sm-8 post">
    <p class="post-text">{{ post.text|linebreaksbr }}</p>
    <footer class="post-footer">
      {% if user.is_superuser %}
        <a href="{%	url	'update_post'	pk=post.pk	%}">edit</a> <a href="{%	url	'delete_post'	pk=post.pk	%}">delete</a>
      {% endif %}
    </footer>
  </div>
</div>
{% endblock %}

templates/blog/blog_posts.html
{% extends 'core/base.html' %}
{% load staticfiles %}
{% load bleach_tags %}

{% block content %}
<div class="col-sm-offset-2 col-sm-8">
  {% if user.is_superuser %}
    <div class="row btn-admin">
      <a href="{% url 'blog:blog_admin' %}"><button class="btn pull-right">Admin</button></a>
    </div>
  {% endif %}
  <div class="row blog-header-row">
  </div>
  <div class="row post-row bg-white">
    {% for post in posts %}
    <div class="post-container">
      <div class="col-sm-2 post-header">
        <div class="post-title text-right dotted-bottom">{{	post.title	}}</div>
        <div class="post-date">{{ post.published_date.date }}</div>
        <div class="post-date">{{ post.published_date.time }}</div>
      </div>
      <div class="col-sm-8 post">
        <p class="post-text">{{ post.text|bleach|linebreaksbr }}</p>
        <footer class="post-footer">
        </footer>
      </div>
      <div class="clearfix"></div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

templates/core/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Rudix Jrinkx</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="http://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <!--static files -->
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body class="bg-white">
{% block menu %}
  {% include 'core/menu.html' %}
{% endblock %}
  <div class="container-fluid">
    {% block content %}{% endblock %}
  </div>
{% block footer %}
  {% include 'core/footer.html' %}
{% endblock %}
</body>

templates/core/footer.html
<footer class="text-center footer">
    <div><sup>&copy;</sup> Rudix Jrinkx</div>
</footer>

templates/core/menu.html
<nav class="navbar navbar-fixed-top top-navbar">
  <div class="container">
    <div class="navbar-header" style="border:0;outline:0">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#top-navbar">
        <span class="icon-bar bg-black"></span>
        <span class="icon-bar bg-black"></span>
        <span class="icon-bar bg-black"></span>
      </button>
      <a class="navbar-brand">Rudix Jrinkx</a>
    </div>
    <div class="collapse navbar-collapse" id="top-navbar">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/">Home</a></li>
        <li><a href="/blog">Blog</a></li>
        <li><a href="https://github.com/jrinkx">GitHub</a></li>
        <li><a href="">About</a></li>
      </ul>
    </div>
  </div>
</nav>

templates/dreamnight/homepage.html
{% extends 'core/base.html' %}
{% load staticfiles %}
{% block content %}
  <div class="row">
    <div class="container-fluid text-center">
      <h2><b>Rudix Jrinkx</b></h2>
      <img src="{% static 'img/logo.png' %}" class="img-responsive img-circle" style="display:inline" alt="Rudix Jrinkx" width="300" height="300">
      <p style="padding-top:15px;">Ku kutip banyak kata dari mereka yang tekemuka,<br />
        hanya untuk melepas dahagaku akan arti kehidupan.</p>
    </div>
  </div>
  <!-- supporter tools -->
  <div class="row">
    <div class="container my-tools">
      <div class="row col-sm-12">
        <div class="col-sm-4 text-center" style="padding:0 30px;">
          <img src="{% static 'img/gnu-linux.png' %}" class="img img-responsive" width="400" height="100">
          <h5 style="clear: left;">Berawal dari <i>newbei</i> yang selalu penasaran untuk mencoba, hingga akhirnya terinfeksi akut dengan GNU/Linux OS.<h5>
        </div>
        <div class="col-sm-4 text-center" style="padding:0 30px;">
          <img src="{% static 'img/django.png' %}" class="img img-responsive" width="400" height="100">
          <h5 style="clear: left;">Python adalah salah satu bahasa program yang selalu hadir hampir di setiap distro GNU/Linux.
          Tentunya menarik untuk dipelajari dan akhirnya membawa saya ke Django framework.<h5>
        </div>
        <div class="col-sm-4 text-center" style="padding:0 30px;">
          <img src="{% static 'img/coffee.png' %}" class="img img-responsive" width="400" height="100">
          <h5 style="clear: left;">Komputer + Internet + Secangkir coffee merupakan paket komplit yang pas untuk menghabiskan waktu.<h5>
        </div>
      </div>
    </div>
  </div>
{% endblock %}